
---
# tasks file for container-image-service

- name: Add gcloud key
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add gcloud repos
  become: yes
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt cloud-sdk main"
    update_cache: yes

- name: Install google-cloud-sdk
  become: yes
  apt:
    name: google-cloud-sdk
    state: present
    update_cache: true

- name: Verify google-cloud-sdk installation
  command: gcloud info
  register: out

- debug: var=out.stdout_lines


- name: Ensures /home/{{ system_user }}/.gcp dir exists
  file: path=/home/{{ system_user }}/.gcp state=directory

- name: Copy service account file
  copy:
    src: ../templates/gcr-account.json
    dest: /home/{{ system_user }}/.gcp/gcr-account.json
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: u+r+x

- name: Tell haylard the gcr settings
  shell: |
    SERVICE_ACCOUNT_NAME=spinnaker-gcr-account
    PASSWORD_FILE=~/.gcp/gcr-account.json
    ADDRESS=gcr.io
    hal config provider docker-registry enable
    hal config provider docker-registry account add gcr-docker-registry  --address $ADDRESS  --username _json_key --password-file $PASSWORD_FILE


