---
# tasks file for config

- name: Ensures /home/{{ system_user }}/.kube dir exists
  file: path=/home/{{ system_user }}/.kube state=directory

# The following task just copy a kubeconfig file. You must provide it 
- name: Copy kubeconfig file to be able to manage k8s
  copy:
    src: ../templates/kubeconfig
    dest: /home/{{ system_user }}/.kube/config
    owner: "{{ system_user }}"
    group: "{{ system_user }}"

- name: Adding account (First make sure that the provider is enabled)
  command: hal config provider kubernetes enable

- name: Adding account (hal config provider kubernetes account add k8s-cluster --context $CONTEXT)
  shell: |
    CONTEXT=$(kubectl config current-context)
    hal config provider kubernetes account add k8s-cluster --context $CONTEXT

- name:   Tell Halyard in what type of environment to install Spinnaker (localdebian)
  command: hal config deploy edit --type localdebian


